define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "AddColor": "Add Color",
    "ChartBar": "Bar",
    "ChartBarHorizontal": "Bar (Horizontal)",
    "ChartData": "Chart Data",
    "ChartDonut": "Donut",
    "ChartLine": "Line",
    "ChartPie": "Pie",
    "ChartSettings": "Chart Settings",
    "ChartStyle": "Chart Style",
    "ChartTitle": "Chart Title",
    "ChartType": "Chart Type",
    "Colors": "Colors",
    "DeleteColor": "Delete",
    "Error": "Something went wrong!",
    "Intro": "Select a list to continue...",
    "List": "List",
    "Loading": "Loading...",
    "LoadingChartData": "Loading chart data...",
    "PropertyPaneDescription": "Dash Settings",
    "Refresh": "Refresh",
    "SelectedFields": "Selected Fields",
  }
});